### ISSUE TITLE
Incorrect REST call when using chatflow soultions

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_threebot#631] opened 2020-04-29 21:03 UTC
Trying to open any of the solutions in chatflow (Network / Ubuntu / etc. ) using https://localhost:4000 makes a REST
call to https://localhost/zerobot/webinterface/actors/chatbot/session_new
while the web interface is running on port 4000. This makes the chatbot
progress ball spin infinitely.

if I use the host system's ethernet address instead of localhost, I get the same problem -- the REST call uses port 80 instead of 4000
- env 
3sdk 10.5
Docker 2.2.0.5
macOS 10.15.3

**Comment by xmonader** [comment] 2020-04-29 21:16
duplicate of https://github.com/threefoldtech/jumpscaleX_threebot/issues/628

**Closed by xmonader** 2020-04-29 21:16 UTC
Labels: priority_critical
