### ISSUE TITLE
Gitea Solution Package

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#153] opened 2019-10-28 15:33 UTC
Child of https://github.com/threefoldtech/home/issues/409

flist: https://hub.grid.tf/nashaatp/gitea.flist.md

# models
```
@url = tfgridsolutions.gitea.instance.1
@acl = false
name** = ""
description = ""
state = "INIT, OK, ERROR"
```

Note: I think we should add deployment info as well on the model

# actor (gitea)

- getall: lists all the deployed instances of igtea 
- chatbot_install_url_get: get solution deployment chatbot url
- wiki_solution_doc_url_get: solution wiki url
- chatbot_recovery_url_get: TBD
- delete: deletes a certain instance 
- monitor_up: check if the solution is up & running (specific to the application)

# Chatflows

Ask user for the following:

- Instance title: str
- Admin username: str
- Admin userpassword: password
- Admin email: str

> later Ask for postgres instance to use (let's use local postgres bundled with the flist for now)

- After successful reservation we should have a container IP or/and create a domain for the instance to use as the ROOT_URL

- Launch the flist `flist url` with 

environment variables 
- `POSTGRES_DB`: gitea 
- `DB_TYPE`: postgres
- `DB_HOST`: localhost:5432
- `DB_USER`: postgres
- `DB_PASSWORD`: postgres
- `APP_NAME`: Instance title from chatflow
- `ADMIN_USER`: Admin username from chatflow
- `ADMIN_PASSWORD`: Admin password from chatflow
- `ADMIN_EMAIL`: Admin email from chatflow
- `ROOT_URL`: IP or domain

**Comment by xmonader** [comment] 2019-11-03 07:56
@despiegk Do you have any comments regarding gitea solution?

**Comment by ranatrk** [comment] 2019-11-11 17:13
Fixed some issues in the loading of the gitea chatflow package and added initial user input in the chatflow.
https://github.com/threefoldtech/jumpscaleX_threebot/commit/0b5da2e15c351c89a9bff3650111b06f38753fc0

**Comment by zaibon** [comment] 2020-05-11 12:05
duplicate of https://github.com/threefoldtech/home/issues/544

**Comment by xmonader** [comment] 2020-05-11 12:05
duplicated of https://github.com/threefoldtech/home/issues/544

**Closed** 2020-05-11 12:05 UTC
