### ISSUE TITLE
rounding issue in payment

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#651] opened 2020-05-03 09:33 UTC
I think we do have a rounding issue in the payment flow.
I made this reservation https://explorer.testnet.grid.tf/explorer/reservations/459798.

The amount asked to be paid was 98.066682 TFT.
But if I check the amount transered: https://stellar.expert/explorer/testnet/tx/272318106443776#272318106443777 it only show 98.06668.

**Comment by waleedhammam** [comment] 2020-05-04 10:41
I tried the following scenarios, on testnet and using TFT

and in all cases I got it right, couldn't reproduce

## Deploy Ubuntu

![1](https://user-images.githubusercontent.com/10658229/80957613-ce92e180-8e03-11ea-890e-be2e5840fa4c.png)
___
![1_1](https://user-images.githubusercontent.com/10658229/80957609-cd61b480-8e03-11ea-9148-a84ed0e783e0.png)
___

## Deploy minio

![2](https://user-images.githubusercontent.com/10658229/80957831-3cd7a400-8e04-11ea-9c87-38889074d08d.png)
___
![2_2](https://user-images.githubusercontent.com/10658229/80957835-3fd29480-8e04-11ea-848e-86bbdec76693.png)
___
![3](https://user-images.githubusercontent.com/10658229/80957849-47923900-8e04-11ea-821d-b1fcaf4dba04.png)
___
![3_3](https://user-images.githubusercontent.com/10658229/80957854-4a8d2980-8e04-11ea-9689-ace52be9e278.png)
___

## Deploy Kubernetes

![4](https://user-images.githubusercontent.com/10658229/80957866-511ba100-8e04-11ea-83fe-71915cfe2036.png)
___
![4_4](https://user-images.githubusercontent.com/10658229/80957873-537dfb00-8e04-11ea-88a3-e2d213f3c181.png)
___

**Comment by zaibon** [comment] 2020-05-04 11:30
The problem has already been reproduced
```python
JSX> amount                                                                                                                                                                     
98.066682

JSX> j.clients.stellar.mywallet.transfer("GDKNF2MV4PH47EZRMJKFYUA5GUEIJFAKIHUFPCU5XFV56W4UCRACTTLR", amount, 'TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3')    
'4adb8833792348bbd514ab3d0d8331f2c7799d52f75e00d1b3ed9878c85d50fb'
```

https://stellar.expert/explorer/testnet/tx/4adb8833792348bbd514ab3d0d8331f2c7799d52f75e00d1b3ed9878c85d50fb

**Comment by DylanVerstraete** [comment] 2020-05-04 11:44
> The problem has already been reproduced
> 
> ```python
> JSX> amount                                                                                                                                                                     
> 98.066682
> 
> JSX> j.clients.stellar.mywallet.transfer("GDKNF2MV4PH47EZRMJKFYUA5GUEIJFAKIHUFPCU5XFV56W4UCRACTTLR", amount, 'TFT:GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3')    
> '4adb8833792348bbd514ab3d0d8331f2c7799d52f75e00d1b3ed9878c85d50fb'
> ```
> 
> https://stellar.expert/explorer/testnet/tx/4adb8833792348bbd514ab3d0d8331f2c7799d52f75e00d1b3ed9878c85d50fb

Where did you get this amount from? It should be 7 digits precision and not 6

**Comment by DylanVerstraete** [comment] 2020-05-04 11:45
Seems like I made a mistake here: https://github.com/threefoldtech/jumpscaleX_libs/blob/59f7230334f3e1cf8f31f7d16ebd86d9890abdb4/JumpscaleLibs/sal/zosv2/billing.py#L26

**Comment by DylanVerstraete** [comment] 2020-05-04 11:55
Fixed in: https://github.com/threefoldtech/jumpscaleX_libs/commit/eb47929fb09babc273c078d78feabde8d1ebbdf2

@zaibon can you pull libs and check?

**Comment by grimpy** [comment] 2020-05-04 15:17
@DylanVerstraete in the scenario above it was reproduced by only using the stelar client, so i doubt your fix solves this one

**Comment by DylanVerstraete** [comment] 2020-05-04 15:18
The stellar client does not do any rounding.. It just takes the input as string and submits that in a transactions..

**Comment by DylanVerstraete** [comment] 2020-05-04 15:20
> @DylanVerstraete in the scenario above it was reproduced by only using the stelar client, so i doubt your fix solves this one

and where did this `amount` variable come from?

**Comment by DylanVerstraete** [comment] 2020-05-05 14:13
Okay some weird stuff happens. We are trying to pay for `1050667160` stropes for a certain reservation in the chatflow. When the actual transaction is submitted we see that the amount in the transaction is correct: `105.066716`

For some reason it transfered only `105.06671` to the escrow account.

We checked sending `105.066716` between wallets with the stellar client and all of these transactions (funded and not funded) succeeded.

This might be an issue on Stellar side...

**Comment by DylanVerstraete** [comment] 2020-05-06 12:56
followup issue: https://github.com/threefoldfoundation/tft-stellar/issues/127

**Closed** 2020-05-06 14:53 UTC
Labels: priority_critical, type_bug
