### ISSUE TITLE
container delete wizard

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#538] opened 2020-04-05 08:24 UTC
show containers, delete them

- Requires separating the network reservation from the rest of reservation (done already)
- Requires keeping track of workloads per solution/reservation https://github.com/threefoldtech/jumpscaleX_threebot/issues/529

**Comment by grimpy** [comment] 2020-04-06 13:33
Closing as duplicate of #529

**Closed by grimpy** 2020-04-06 13:33 UTC
Labels: type_feature
