### ISSUE TITLE
Too many cert issued for wiki [unstable_ssl]

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/jumpscaleX_threebot#469] opened 2020-03-24 07:54 UTC
vm access : ``` ssh root@157.245.87.227 ```
threebot commit : 3820751b86e49f5afbb8d60706b07d904469b420
link : https://wiki2.tokens.grid.tf/#/

```
”detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
```
![2020-03-24 09 52 17](https://user-images.githubusercontent.com/13523434/77401215-3130a080-6db5-11ea-9a06-b84b0d140f80.jpg)

**Comment by waleedhammam** [comment] 2020-03-24 10:10
checking the root cause that led to many failure certs

**Comment by waleedhammam** [comment] 2020-03-24 16:40
Fixed in pr at: https://github.com/threefoldtech/jumpscaleX_core/pull/661/files

test at: https://waleed2.grid.tf/auth/login?next_url=/admin

![Screenshot from 2020-03-24 18-39-58](https://user-images.githubusercontent.com/10658229/77452709-ee93b600-6dfe-11ea-972e-8c422f154b4a.png)

**Comment by waleedhammam** [comment] 2020-03-25 07:37
- Note: you may have to clean locations after this fix so that  it's not interfered with old ones using
`j.servers.openresty.default_openresty_threebot.websites.delete()`

**Comment by hossnys** [comment] 2020-03-25 08:11
verified 

![Screenshot from 2020-03-25 10-11-17](https://user-images.githubusercontent.com/26298009/77515240-d82e3e80-6e80-11ea-9e93-cd131af67804.png)

**Closed by hossnys** 2020-03-25 08:11 UTC
Labels: type_bug
