### ISSUE TITLE
ubuntu & 3bot flist have std ssh on & std login/passwd

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#539] opened 2020-04-05 09:00 UTC
- know its not ideal but at least we can continue
- the experience now is too cumbersome
- this allows automated solutions to work

**Comment by xmonader** [comment] 2020-04-05 14:39
duplicate of https://github.com/threefoldtech/jumpscaleX_threebot/issues/524

**Closed by xmonader** 2020-04-05 14:39 UTC
Labels: type_feature
