### ISSUE TITLE
registration actor: reseed failed

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#222] opened 2019-11-12 09:26 UTC
I was testing the reseed method that is supposed to be used when initialization a 3bot, but got this error:

```
3BOTDEVEL:3bot:~: kosmos -p 'system = j.data.bcdb.get_system(); system.import_("/tmp/jumpscale/se147c6230")'
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.server
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.oauth_proxy.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_custom
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_lapis
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_proxy
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_static
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.server.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.website
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.peewee.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.rdb.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.redis_config.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.me
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.package.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot_server.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.client.1
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.server.1
Tue 12 09:24:36 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
Tue 12 09:24:36 BCDB.py              - 394 - bcdb                               : STOP BCDB
Tue 12 09:24:36 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Tue 12 09:24:36 DBSQLite.py          -  91 - dbsqlite                           : RESET FOR KVS
Tue 12 09:24:36 BCDB.py              - 179 - bcdb                               : Load bcdb:system from /tmp/jumpscale/se147c6230
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.server
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.oauth_proxy.client
Tue 12 09:24:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_custom
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_lapis
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_proxy
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.location_static
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.server.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.openresty.website
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.peewee.client
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.rdb.client
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.redis_config.client
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.client
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.client
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.me
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot.package.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.threebot_server.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.client.1
Tue 12 09:24:37 BCDB.py              - 446 - bcdb                               : load model:jumpscale.zdb.server.1
Tue 12 09:24:37 db39ba5615b225d6b.py -  31 - 1_a2ceb60df57b6ecdb39ba5615b225d6b : init index:jumpscale.threebot_server.1
Tue 12 09:24:37 09aa584ed5df75f46.py -  31 - 1_9faa8cee419d47709aa584ed5df75f46 : init index:jumpscale.startupcmd.1
Tue 12 09:24:37 99aa9ab6c282bc932.py -  31 - 1_76f6215e7a241d899aa9ab6c282bc932 : init index:jumpscale.openresty.server.1
Tue 12 09:24:38 le/data/bcdb/BCDB.py - 256 - import_                            : EXCEPTION: 
    AssertionError()
--TRACEBACK------------------
<string> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py in import_
    256    assert obj.id == i
-----------------------------

Tue 12 09:24:39 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
3BOTDEVEL:3bot:~: 

```

**Comment by serboctor** [comment] 2019-11-12 11:51
I can't reproduce it at all. I repeated the same steps like the actor, and it went smoothly with me.
Here are my steps below:
1- On a clean bcdb, I created a new gedis client, so I can check it exists after I re-import the data.
```
JSX> j.clients.gedis.get(name="main", host="explorer.testnet.grid.tf", port=8901)                                                                                                                           
# JSXOBJ:
## .gedis.client
ID: 3
 - name                : main
 - host                : explorer.testnet.grid.tf
 - port                : 8901
 - namespace           : default
 - threebot_local_profile: default
 - password_           : 



JSX> _.save() ```

2- Generate  a new seed, export the data, configure nacl, and import the data.
```
JSX> from nacl import signing                                                                                                                                                                               
   1  
   2 s = signing.SigningKey.generate()                                                                                                                                                                      
...   
   3 seed =j.data.encryption.mnemonic.to_mnemonic(s._seed)                                                                                                                                                  
JSX> exportpath = j.sal.fs.getTmpDirPath() 
   2 j.data.bcdb.system.export(exportpath, False)                                                                                                                                                           
JSX> j.data.nacl.configure(privkey_words=seed, reset=True)                                                                                                                                                  
nacl:default
JSX> j.sal.process.execute(f"kosmos -p 'system = j.data.bcdb.get_system(); system.import_(\"{exportpath}\")'")                                                                                              
Tue 12 11:36:35 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Tue 12 11:36:35 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Tue 12 11:36:35 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Tue 12 11:36:35 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Tue 12 11:36:35 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Tue 12 11:36:35 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
Tue 12 11:36:35 BCDB.py              - 394 - bcdb                               : STOP BCDB
Tue 12 11:36:35 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Tue 12 11:36:36 DBSQLite.py          -  91 - dbsqlite                           : RESET FOR KVS
Tue 12 11:36:36 BCDB.py              - 179 - bcdb                               : Load bcdb:system from /tmp/jumpscale/0cx8t9msyi
Tue 12 11:36:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Tue 12 11:36:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Tue 12 11:36:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Tue 12 11:36:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Tue 12 11:36:36 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Tue 12 11:36:36 585676b6b8a623905.py -  31 - 1_2793961a89d4ca4585676b6b8a623905 : init index:jumpscale.sonic.server.1
Tue 12 11:36:36 09aa584ed5df75f46.py -  31 - 1_9faa8cee419d47709aa584ed5df75f46 : init index:jumpscale.startupcmd.1
Tue 12 11:36:36 3b380bdd704da6e8d.py -  31 - t_f870d416e3720c73b380bdd704da6e8d : init index:jumpscale.gedis.client
Tue 12 11:36:37 BCDB.py              - 338 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
(0, '\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.bcdb.acl.circle.2\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.bcdb.acl.user.2\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.gedis.client\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.sonic.server.1\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.startupcmd.1\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m -  87 - \x1b[0;37mbcdb                               \x1b[0;0m: BCDB INIT DONE:system\n\x1b[1;34mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 394 - \x1b[0;37mbcdb                               \x1b[0;0m: STOP BCDB\n\x1b[0;33mTue 12 11:36:35 BCDB.py             \x1b[0;0m - 338 - \x1b[0;37mbcdb                               \x1b[0;0m: DATAPROCESSOR & SQLITE STOPPED OK\n\x1b[1;34mTue 12 11:36:36 DBSQLite.py         \x1b[0;0m -  91 - \x1b[0;37mdbsqlite                           \x1b[0;0m: RESET FOR KVS\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 179 - \x1b[0;37mbcdb                               \x1b[0;0m: Load bcdb:system from /tmp/jumpscale/0cx8t9msyi\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.bcdb.acl.circle.2\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.bcdb.acl.user.2\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.startupcmd.1\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.gedis.client\n\x1b[1;34mTue 12 11:36:36 BCDB.py             \x1b[0;0m - 446 - \x1b[0;37mbcdb                               \x1b[0;0m: load model:jumpscale.sonic.server.1\n\x1b[1;34mTue 12 11:36:36 585676b6b8a623905.py\x1b[0;0m -  31 - \x1b[0;37m1_2793961a89d4ca4585676b6b8a623905 \x1b[0;0m: init index:jumpscale.sonic.server.1\n\x1b[1;34mTue 12 11:36:36 09aa584ed5df75f46.py\x1b[0;0m -  31 - \x1b[0;37m1_9faa8cee419d47709aa584ed5df75f46 \x1b[0;0m: init index:jumpscale.startupcmd.1\n\x1b[1;34mTue 12 11:36:36 3b380bdd704da6e8d.py\x1b[0;0m -  31 - \x1b[0;37mt_f870d416e3720c73b380bdd704da6e8d \x1b[0;0m: init index:jumpscale.gedis.client\n\x1b[0;33mTue 12 11:36:37 BCDB.py             \x1b[0;0m - 338 - \x1b[0;37mbcdb                               \x1b[0;0m: DATAPROCESSOR & SQLITE STOPPED OK\n', '')```

3- restart kosmos, and check the gedis client instance exists.
```
3BOTDEVEL:e069892db594:/: kosmos -p
Tue 12 11:37:25 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Tue 12 11:37:25 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Tue 12 11:37:25 BCDB.py              - 446 - bcdb                               : load model:jumpscale.gedis.client
Tue 12 11:37:25 BCDB.py              - 446 - bcdb                               : load model:jumpscale.sonic.server.1
Tue 12 11:37:25 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Tue 12 11:37:25 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
JSX> j.clients.gedis.main                                                                                                                                                                                   
# JSXOBJ:
## .gedis.client
ID: 3
 - name                : main
 - host                : explorer.testnet.grid.tf
 - port                : 8901
 - namespace           : default
 - threebot_local_profile: default
 - password_           : 
```

**Comment by serboctor** [comment] 2019-11-12 12:17
We'll look into it again and try to somehow reproduce the error after we're done with other high prio tasks.
@zaibon if there is anything you can tell us about the data you had that would help in anyway, please do.

**Comment by MathiasDeWeerdt** [comment] 2019-11-12 13:11
I just managed to reproduce this error.

I usually run the docker instance with the follow command(s)
`docker restart NAME && docker exec -it NAME /bin/bash -c ". /sandbox/env.sh && . /sandbox/clear.sh && js_init generate && kosmos -p"`

The clear.sh script looks has the following content:
```
#!/bin/bash
echo "CLEARING ALL BCDB"
kosmos 'j.data.bcdb.destroy_all()'
pkill redis -9
pkill redis-server -9
kosmos 'j.application.bcdb_system_destroy()'
echo "CLEARING OK"
```

When trying to reseed on a "clean" instance of the 3bot it seems to be working fine.

**Comment by RafyAmgadBenjamin** [comment] 2019-11-13 11:30
The importing in BDCB is fixed now.

**Comment by RafyAmgadBenjamin** [comment] 2019-11-13 14:34
I have made a check that if the object from BCDB model has a name attribute before setting GUID to it.
https://github.com/threefoldtech/jumpscaleX_core/pull/220

**Comment by Pishoy** [comment] 2019-11-14 07:54
am still facing the same error 
```
3BOTDEVEL:jsx:~: kosmos -p 'system = j.data.bcdb.get_system(); system.import_("/tmp/jumpscale/se147c6230")'

3BOTDEVEL:jsx:jumpscaleX_core: kosmos -p 'system = j.data.bcdb.get_system(); system.import_("/tmp/jumpscale/se147c6230")'
Thu 14 07:53:20 BCDB.py              - 448 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Thu 14 07:53:20 BCDB.py              - 448 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Thu 14 07:53:20 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
Thu 14 07:53:20 BCDB.py              - 396 - bcdb                               : STOP BCDB
Thu 14 07:53:20 BCDB.py              - 340 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Thu 14 07:53:20 DBSQLite.py          -  91 - dbsqlite                           : RESET FOR KVS
Thu 14 07:53:21 BCDB.py              - 179 - bcdb                               : Load bcdb:system from /tmp/jumpscale/se147c6230
Thu 14 07:53:21 le/data/bcdb/BCDB.py - 180 - import_                            : EXCEPTION: 
    AssertionError()
--TRACEBACK------------------
<string> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py in import_
    180    assert j.sal.fs.exists(path)
-----------------------------

Thu 14 07:53:22 BCDB.py              - 340 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK

```
- jsx version 
```
commit 5a0fce4a38dc86333502aa8e6a8cf15a51b99c9d (HEAD -> development, origin/development, origin/HEAD)
Author: john-kheir <john.kheir33@gmail.com>
Date:   Thu Nov 14 08:40:17 2019 +0200

    registry client tests (#224)
    
    * registery client tests
    
    * future-work

```

**Comment by serboctor** [comment] 2019-11-14 08:51
@Pishoy that's not the same error. This error is because you're trying to import a file that doesn't exist on your system. You can't just use the same file that @zaibon was using, he had this file as a result of the import. Please check my comment on the ticket, it has steps that you can use to check the whole scenario.

**Comment by Pishoy** [comment] 2019-11-14 09:26
verified

**Closed by Pishoy** 2019-11-14 09:26 UTC
Labels: priority_critical, state_verification, type_bug
